### ISSUE TITLE
Consider using RFC-6570 for routing config

### ISSUE THREAD

**Issue by Ocramius** [DASPRiD/Dash#35]
See https://tools.ietf.org/html/rfc6570 - much better than yet another custom format

Could that be implemented as a single route type?

**Comment by DASPRiD** [comment]
This can be completely done in your own route class, no need for the core router to support it by itself.

**Comment by Ocramius** [comment]
This should be reopened, IMO.

While we have our own (proprietary) format for routes, the point of this issue is that we should stop doing that (proprietary format), and use something that is actually standardized in future.

The point of moving it to core Dash is not to make Dash more complex, but slowly deprecate the proprietary approach for well known standards (at least for the more simplistic routes).

**Comment by DASPRiD** [comment]
I have to disagree with that. I've gone over that RFC quite a few times already in the past, and my point is still valid. As the RFC says itself, it is not suited for matching URLs, but only building them. That would mean to make the route definitions more complex for users, as they'd always have to supply a matching pattern in a different language (e.g. regex). Not only that, but the RFC pattern also does not account for optional components or, what some users also use, translatable literals.

URI templates are great for defining complete URLs to external resources which don't follow a standard format like REST, but for internal routing, they don't supply any advantage, ignoring the fact that parsing the RFCs ABNF would be quite resource intensive compared to our rather simple format.
