### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by bakura10** [DASPRiD/Dash#36]
For @DASPRiD: https://github.com/c9s/Pux

I know nothing about how this project work, it's full of obscure thing, but maybe it makes sense to you and it could give you some nice ideas to optimize Dash.

**Comment by DASPRiD** [comment]
It actually has some quite interesting approaches, by compiling every route into a regex, matching against a prepared request string. Of course, the downside of it is, that it can't handle extensions, so it's quite limited. Thanks for hinting me though :)
