### ISSUE TITLE
Introduce benchmarks

### ISSUE THREAD

**Issue by bakura10** [DASPRiD/Dash#41]
Hi,

It would be awesome if you could move some of your benchmark code directly into Dash. As a rule of thumb, I'd like if we could have this in ZF3 for all critical performance components. That would allow for much simpler optimization work (as we would have a true before/after), as well as being able to quickly have a look at the impact of a new feature on performance, and eventually rejecting it (I'm thinking here about input filter that has many features introduced, without taking care of performance, so now this component is really slow - if we had that we could have quickly rejected some feature, or refactoring them).

**Comment by DASPRiD** [comment]
Addressed with e7917933e8175110ceb8bd32ccf73f7b466063b3 – Thanks for the suggestion :)
