### ISSUE TITLE
Zend Uri

### ISSUE THREAD

**Issue by harikt** [DASPRiD/Dash#55]
Hi @DASPRiD , 

I was looking into dash, and noticed it is making use of zf2 uri component.

Is it really needed?

If you look uri, it makes use of 

        "zendframework/zend-escaper": "self.version",
        "zendframework/zend-validator": "self.version"

I have looked at some of the routing libraries like aura, symfony etc. But haven't noticed something like a uri is really needed. Is there any extra behavior I am missing to understand ?

It may be good if router can reduce the amount of components which are not really needed.

Thank you

**Comment by DASPRiD** [comment]
This is solved with the refactoring #54, where we solely rely on PSR-7 now which supplies an URI interface.

**Comment by harikt** [comment]
Closing in favor of #54.
